### ISSUE TITLE
Impossible to make ancient debris

### ISSUE THREAD

**Issue by Hedger368** [dedouwe26/Minecraft-Datapacks#1]
Recipe for ancient debris requires 2 ancient debris, 2 gilded blackstone, 2 netherrack, 2 basalt and 405000mb of lava. Recipe is impossible due to not being able to fit that much lava in a single basin

**Comment by dedouwe26** [comment]
o

**Comment by dedouwe26** [comment]
Thx for reporting it. I'll fix it as soon as possible

**Comment by dedouwe26** [comment]
Btw, in the fabric version of Create, the 405000mB actually is 5000mB.
